# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDJDHpohDRz-0AoIX2X6QLo0NDYYmaun
"""

productos = []

def añadir_producto():
  productos.append({
      'nombre': input('Nombre del producto: '),
      'precio': float(input('Precio del producto: ')),
      'cantidad': int(input('Cantidad de productos: '))
  })

def ver_productos():
  if not productos:
    print("No hay productos en la lista.")
  else:
    print(productos)

def actualizar_producto():
  i = int(input('Ingrese el indice del producto a modificar')) - 1
  if 0 <= i < len(productos):
    nomb = int(input('Seleccione un numero: \n1.Nombre \n2.Precio \n3.Cantidad \n'))
    if nomb == 1:
        productos[i]['nombre'] = input('Ingrese nuevo nombre:')
    elif nomb == 2:
        productos[i]['precio'] = input('Ingrese nuevo precio:')
    elif nomb == 3:
        productos[i]['cantidad'] = input('Ingrese nueva cantidad:')
    else:
        print('Opcion no valida')
  else:
       print('Elemento no existe')

def eliminar_producto():
  i = int(input('Ingrese el indice del producto a eliminar')) - 1
  if 0 < i < len(productos):
    del productos[i]
  else:
    print('Elemento no existe')

def guardar_datos():
    datos = open("data.txt", 'w')
    for i in productos:
      datos.write(f"{i['nombre']},{i['precio']},{i['cantidad']}\n")
    datos.close()
    print('Datos se han guardado, Adios!')


def cargar_datos():
  try:
    datos = open("data.txt", 'r')
    global productos
    productos = []
    for i in datos:
      nombre, precio, cantidad = i.split(',')
      productos.append({'nombre': nombre,
                        'precio': float(precio),
                        'cantidad': int(cantidad)})
    print('Datos cargados con exito')
    print(productos)
    datos.close()
  except FileNotFoundError:
    print('No se encontro el archivo')
  except ValueError:
    print('Hubo un error')

def menu():
    while True:
        print("1: Añadir producto")
        print("2: Ver productos")
        print("3: Actualizar producto")
        print("4: Eliminar producto")
        print("5: Guardar datos y salir")
        print("6: Cargar datos")

        opcion = input("Selecciona una opción: ")

        if opcion == '1':
            añadir_producto()
        elif opcion == '2':
            ver_productos()
        elif opcion == '3':
            actualizar_producto()
        elif opcion == '4':
            eliminar_producto()
        elif opcion == '5':
            guardar_datos()
            break
        elif opcion == '6':
            cargar_datos()
        else:
            print("Por favor, selecciona una opción válida.")

menu()